### ISSUE TITLE
racist send button no refresh page go brr

### ISSUE THREAD

**Issue by ErdaBerda** [OrnitOnGithub/lan-chatroom#6]
<script>
                document.querySelector('form').addEventListener('submit', function(event) {
                event.preventDefault(); // Prevent the default form submission

                const textInput = document.getElementById('text');
                const textValue = textInput.value;

                // Submit the form data via AJAX
                fetch('/add_text', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                    },
                    body: new URLSearchParams({
                        text: textValue
                    })
                }).then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.text();
                }).then(data => {
                    // Update the chat box with the new message
                    document.getElementById('file-content').innerHTML += '<br>' + textValue;
                    textInput.value = ''; // Clear the input field
                }).catch(error => {
                    console.error('There has been a problem with your fetch operation:', error);
                });
            });
            </script>

**Comment by OrnitOnGithub** [comment]
Danke schön, implemented.
